//! Session conformance tests (ISO 18013-5 §9.1).
//!
//! Verifies:
//!   - §9.1.1  SessionKeyAgreement: both parties derive the same shared secret
//!   - §9.1.3  SessionEncryption:  encrypt → decrypt round-trip
//!   - §9.1.3  Counter management: send/receive counters increment correctly
//!   - §9.1.3  Ciphertext integrity: modified ciphertext must not decrypt
//!   - §9.1.3  AES-256-GCM nonce uniqueness: two encryptions of the same
//!             plaintext produce different ciphertexts (counter-derived nonce)

use marty_iso18013::session::{SessionEncryption, SessionKeyAgreement};

// ── §9.1.1  ECDH key agreement ────────────────────────────────────────────────

/// Both the mDL holder and the mDL reader derive the same shared secret when
/// each holds the other party's public key (ISO 18013-5 §9.1.1).
#[test]
fn session_key_agreement_both_parties_derive_same_secret() {
    let mut holder = SessionKeyAgreement::new().expect("holder key agreement");
    let mut reader = SessionKeyAgreement::new().expect("reader key agreement");

    let holder_pub = holder.public_key();
    let reader_pub = reader.public_key();

    holder.set_peer_key(reader_pub);
    reader.set_peer_key(holder_pub);

    let holder_secret = holder.derive_shared_secret().expect("holder secret");
    let reader_secret = reader.derive_shared_secret().expect("reader secret");

    assert_eq!(
        holder_secret, reader_secret,
        "ISO 18013-5 §9.1.1: both parties must derive the same shared secret"
    );
    assert!(!holder_secret.is_empty(), "shared secret must not be empty");
}

/// Public keys generated by different key agreement instances must be distinct
/// (random ephemeral generation per session).
#[test]
fn session_key_agreement_generates_distinct_ephemeral_keys() {
    let ka1 = SessionKeyAgreement::new().expect("ka1");
    let ka2 = SessionKeyAgreement::new().expect("ka2");

    assert_ne!(
        ka1.public_key(),
        ka2.public_key(),
        "each session must use a fresh ephemeral key pair"
    );
}

/// Public key must be non-empty and plausibly sized for a P-256 point
/// (uncompressed 65 bytes or compressed 33 bytes).
#[test]
fn session_key_agreement_public_key_has_expected_size() {
    let ka = SessionKeyAgreement::new().expect("ka");
    let pk = ka.public_key();

    assert!(
        pk.len() == 65 || pk.len() == 33,
        "P-256 public key must be 65 bytes (uncompressed) or 33 bytes (compressed), got {}",
        pk.len()
    );
}

// ── §9.1.3  SessionEncryption ─────────────────────────────────────────────────

/// A transcript-derived SessionEncryption must encrypt and then decrypt back to
/// the original plaintext.
#[test]
fn session_encryption_round_trip() {
    let shared_secret = [0x42u8; 32];
    let session_transcript = b"test-session-transcript-bytes";

    let mut enc =
        SessionEncryption::new(&shared_secret, session_transcript).expect("SessionEncryption::new");

    let plaintext = b"Hello, ISO 18013-5 session encryption!";
    let ciphertext = enc.encrypt(plaintext).expect("encrypt");

    // A new SessionEncryption on the same keying material for decryption
    let mut dec = SessionEncryption::new(&shared_secret, session_transcript)
        .expect("SessionEncryption::new (dec)");

    let recovered = dec.decrypt(&ciphertext).expect("decrypt");

    assert_eq!(
        recovered, plaintext,
        "decrypted plaintext must match the original"
    );
}

/// Send counter must start at 1 and increment with each encrypt call
/// (ISO 18013-5 §9.1.3 — counter-based nonce prevents nonce reuse).
#[test]
fn session_encryption_send_counter_increments() {
    let shared_secret = [0x01u8; 32];
    let transcript = b"counter-test-transcript";

    let mut enc = SessionEncryption::new(&shared_secret, transcript).expect("create");

    assert_eq!(enc.send_counter(), 0, "initial send counter must be 0");

    enc.encrypt(b"msg1").expect("encrypt 1");
    assert_eq!(enc.send_counter(), 1, "send counter after 1 encryption");

    enc.encrypt(b"msg2").expect("encrypt 2");
    assert_eq!(enc.send_counter(), 2, "send counter after 2 encryptions");

    enc.encrypt(b"msg3").expect("encrypt 3");
    assert_eq!(enc.send_counter(), 3, "send counter after 3 encryptions");
}

/// Receive counter must increment with each successful decrypt call.
#[test]
fn session_encryption_receive_counter_increments() {
    let shared_secret = [0x02u8; 32];
    let transcript = b"receive-counter-transcript";

    let mut enc = SessionEncryption::new(&shared_secret, transcript).expect("enc");
    let mut dec = SessionEncryption::new(&shared_secret, transcript).expect("dec");

    assert_eq!(
        dec.receive_counter(),
        0,
        "initial receive counter must be 0"
    );

    let ct1 = enc.encrypt(b"alpha").expect("encrypt");
    dec.decrypt(&ct1).expect("decrypt");
    assert_eq!(dec.receive_counter(), 1, "receive counter after 1 decrypt");

    let ct2 = enc.encrypt(b"beta").expect("encrypt");
    dec.decrypt(&ct2).expect("decrypt");
    assert_eq!(dec.receive_counter(), 2, "receive counter after 2 decrypts");
}

/// AES-256-GCM counter-based nonces must ensure ciphertext uniqueness:
/// encrypting the same plaintext twice with the same key must produce
/// different ciphertexts (different nonces).
#[test]
fn session_encryption_nonces_are_unique_per_message() {
    let shared_secret = [0x77u8; 32];
    let transcript = b"nonce-uniqueness-transcript";

    let mut enc = SessionEncryption::new(&shared_secret, transcript).expect("enc");

    let ct1 = enc.encrypt(b"same plaintext").expect("encrypt first");
    let ct2 = enc.encrypt(b"same plaintext").expect("encrypt second");

    assert_ne!(
        ct1, ct2,
        "encrypting the same plaintext twice must yield distinct ciphertexts"
    );
}

/// A tampered ciphertext (single bit flip) must fail decryption — AES-GCM
/// authentication tag verification rejects modified data.
#[test]
fn session_encryption_tampered_ciphertext_rejected() {
    let shared_secret = [0x33u8; 32];
    let transcript = b"tamper-test-transcript";

    let mut enc = SessionEncryption::new(&shared_secret, transcript).expect("enc");
    let mut dec = SessionEncryption::new(&shared_secret, transcript).expect("dec");

    let ct = enc.encrypt(b"sensitive data").expect("encrypt");

    // Flip a bit in the ciphertext body (skip any leading nonce/header bytes)
    let flip_pos = ct.len() / 2;
    let mut tampered = ct.clone();
    tampered[flip_pos] ^= 0xFF;

    let result = dec.decrypt(&tampered);
    assert!(
        result.is_err(),
        "tampered ciphertext must not decrypt successfully"
    );
}

/// Encrypting an empty plaintext is permitted (e.g., status messages).
#[test]
fn session_encryption_empty_plaintext_round_trip() {
    let shared_secret = [0xABu8; 32];
    let transcript = b"empty-plaintext-transcript";

    let mut enc = SessionEncryption::new(&shared_secret, transcript).expect("enc");
    let mut dec = SessionEncryption::new(&shared_secret, transcript).expect("dec");

    let ct = enc.encrypt(b"").expect("encrypt empty");
    let recovered = dec.decrypt(&ct).expect("decrypt empty");

    assert!(
        recovered.is_empty(),
        "decrypted empty plaintext must be empty"
    );
}

/// Two independent sessions derived from different shared secrets must not
/// be able to decrypt each other's ciphertexts.
#[test]
fn session_encryption_cross_session_isolation() {
    let secret_a = [0xAAu8; 32];
    let secret_b = [0xBBu8; 32];
    let transcript = b"isolation-transcript";

    let mut enc_a = SessionEncryption::new(&secret_a, transcript).expect("enc_a");
    let mut dec_b = SessionEncryption::new(&secret_b, transcript).expect("dec_b");

    let ct = enc_a.encrypt(b"session A message").expect("encrypt");
    let result = dec_b.decrypt(&ct);

    assert!(
        result.is_err(),
        "a ciphertext from session A must not be decryptable by session B"
    );
}

// ── §9.1.1 + §9.1.3  full handshake integration ──────────────────────────────

/// Full session establishment: ECDH key agreement → derive SessionEncryption
/// → encrypt on holder side → decrypt on reader side.
#[test]
fn session_full_handshake_holder_to_reader() {
    // Key agreement
    let mut holder_ka = SessionKeyAgreement::new().expect("holder ka");
    let mut reader_ka = SessionKeyAgreement::new().expect("reader ka");

    let holder_pub = holder_ka.public_key();
    let reader_pub = reader_ka.public_key();

    holder_ka.set_peer_key(reader_pub);
    reader_ka.set_peer_key(holder_pub);

    let shared = holder_ka.derive_shared_secret().expect("shared secret");

    let transcript = b"SessionTranscript{...}";

    let mut holder_enc = SessionEncryption::new(&shared, transcript).expect("holder enc");
    let mut reader_dec = SessionEncryption::new(&shared, transcript).expect("reader dec");

    let plaintext = b"mDoc response data";
    let ct = holder_enc.encrypt(plaintext).expect("holder encrypt");
    let recovered = reader_dec.decrypt(&ct).expect("reader decrypt");

    assert_eq!(
        recovered, plaintext,
        "full handshake: decrypt must recover plaintext"
    );
}
