#!/usr/bin/env python3
"""
Code generator for marty-types
Generates Rust, Python, and Dart constants from YAML schemas
"""

import os
import sys
from pathlib import Path
from typing import Any, Dict
import yaml
from jinja2 import Environment, FileSystemLoader


def load_schema(schema_path: Path) -> Dict[str, Any]:
    """Load a YAML schema file"""
    with open(schema_path, 'r') as f:
        return yaml.safe_load(f)


def generate_rust_namespaces(schema: Dict[str, Any], output_path: Path):
    """Generate Rust namespace constants"""
    env = Environment(loader=FileSystemLoader(Path(__file__).parent / 'templates'))
    template = env.get_template('rust_namespaces.rs.j2')
    
    content = template.render(schema=schema)
    output_path.write_text(content)
    print(f"Generated Rust namespaces: {output_path}")


def generate_rust_error_codes(schema: Dict[str, Any], output_path: Path):
    """Generate Rust error code enums"""
    env = Environment(loader=FileSystemLoader(Path(__file__).parent / 'templates'))
    template = env.get_template('rust_error_codes.rs.j2')
    
    content = template.render(error_codes=schema['error_codes'])
    output_path.write_text(content)
    print(f"Generated Rust error codes: {output_path}")


def generate_python_namespaces(schema: Dict[str, Any], output_path: Path):
    """Generate Python namespace constants"""
    env = Environment(loader=FileSystemLoader(Path(__file__).parent / 'templates'))
    template = env.get_template('python_namespaces.py.j2')
    
    content = template.render(schema=schema)
    output_path.write_text(content)
    print(f"Generated Python namespaces: {output_path}")


def generate_python_error_codes(schema: Dict[str, Any], output_path: Path):
    """Generate Python error code classes"""
    env = Environment(loader=FileSystemLoader(Path(__file__).parent / 'templates'))
    template = env.get_template('python_error_codes.py.j2')
    
    content = template.render(error_codes=schema['error_codes'])
    output_path.write_text(content)
    print(f"Generated Python error codes: {output_path}")


def generate_dart_namespaces(schema: Dict[str, Any], output_path: Path):
    """Generate Dart namespace constants"""
    env = Environment(loader=FileSystemLoader(Path(__file__).parent / 'templates'))
    template = env.get_template('dart_namespaces.dart.j2')
    
    content = template.render(schema=schema)
    output_path.write_text(content)
    print(f"Generated Dart namespaces: {output_path}")


def generate_dart_error_codes(schema: Dict[str, Any], output_path: Path):
    """Generate Dart error code enums"""
    env = Environment(loader=FileSystemLoader(Path(__file__).parent / 'templates'))
    template = env.get_template('dart_error_codes.dart.j2')
    
    content = template.render(error_codes=schema['error_codes'])
    output_path.write_text(content)
    print(f"Generated Dart error codes: {output_path}")


def main():
    """Main code generation entry point"""
    # Determine paths
    script_dir = Path(__file__).parent
    root_dir = script_dir.parent
    schema_dir = root_dir / 'schema'
    
    # Create output directories
    rust_src = root_dir / 'src' / 'generated'
    python_dir = root_dir / 'python'
    dart_dir = root_dir / 'dart'
    
    rust_src.mkdir(parents=True, exist_ok=True)
    python_dir.mkdir(parents=True, exist_ok=True)
    dart_dir.mkdir(parents=True, exist_ok=True)
    
    # Load schemas
    namespaces_schema = load_schema(schema_dir / 'namespaces.yaml')
    error_codes_schema = load_schema(schema_dir / 'error_codes.yaml')
    
    # Generate Rust
    generate_rust_namespaces(namespaces_schema, rust_src / 'namespaces.rs')
    generate_rust_error_codes(error_codes_schema, rust_src / 'error_codes.rs')
    
    # Generate Python
    generate_python_namespaces(namespaces_schema, python_dir / 'namespaces.py')
    generate_python_error_codes(error_codes_schema, python_dir / 'error_codes.py')
    
    # Generate Dart
    generate_dart_namespaces(namespaces_schema, dart_dir / 'namespaces.dart')
    generate_dart_error_codes(error_codes_schema, dart_dir / 'error_codes.dart')
    
    # Generate mod.rs for Rust
    (rust_src / 'mod.rs').write_text("""//! Generated constants and types
//! DO NOT EDIT - Generated by codegen/generate.py

pub mod namespaces;
pub mod error_codes;
""")
    
    # Generate __init__.py for Python
    (python_dir / '__init__.py').write_text("""# Generated constants and types
# DO NOT EDIT - Generated by codegen/generate.py

from .namespaces import *
from .error_codes import *

__all__ = [
    # Namespaces
    'Iso18013Namespace',
    'Iso18013DocType',
    'Iso18013Element',
    'W3cContext',
    'W3cType',
    'CredentialFormat',
    # Error codes
    'ErrorCode',
]
""")
    
    print("\n✅ Code generation complete!")
    print("\nGenerated files:")
    print(f"  Rust:   {rust_src}/")
    print(f"  Python: {python_dir}/")
    print(f"  Dart:   {dart_dir}/")
    print("\nRemember to run 'cargo fmt' in the Rust directory")


if __name__ == '__main__':
    main()
